/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.wofford;

import java.util.Random;

public class App {
    public static void main(String[] args) {
    	// There's nothing to implement here.
    	// This is just an example of how the class might be used.
        Random random = new Random();
        ConnectFour cf = new ConnectFour();
        int moves = 0;
        while(cf.getResult() == ConnectFour.Result.NONE && moves < 42) {
            int col = random.nextInt(7);
            try {
                cf.dropToken(col);
                System.out.println(cf);
            }
            catch(ColumnFullException e) {}
            moves++;
        }
    }
}
